import Link from "next/link";
import { CopyValue } from "@/components/governance/CopyValue";
import { LiveReadStatus } from "@/components/proof/LiveReadStatus";
import { ACTIVE_NETWORK, voxenConfig } from "@/lib/voxen/config";
import { liveProof } from "@/lib/voxen/proof";

const checks = [["Proposal state", "The contract keeps a proposal’s published, review, and finalized state.", "Deterministic contract logic", "Read the proposal and its lifecycle state afterward."], ["Voting window", "Votes are accepted only within the proposal’s configured start and end time.", "Deterministic contract logic", "Read the recorded window and current proposal state."], ["Eligibility", "The contract checks the proposal’s selected eligibility rule when a vote executes.", "Deterministic contract logic", "Inspect the rule stored with the proposal. PUBLIC means open participation."], ["Final vote enforcement", "The connected sender is subject to the proposal’s duplicate-vote and vote-change policy.", "Deterministic contract logic", "Inspect the policy and resulting tally. This does not prove a sender is a unique person."], ["Tallies and lifecycle", "Vote totals, finalization, and tied outcomes are stored as contract state.", "Deterministic contract logic", "Read tallies and the final result after lifecycle handling."], ["Governance Review", "Where a Community requires it, validators assess supplied rules and evidence before publication.", "Validator consensus", "Read the recorded review outcome. It informs governance and does not override votes."]] as const;

export default function LiveProof() {
  return <main id="main" className="shell page proof-page">
    <header className="proof-header"><div><span className="eyebrow"><i className="live-dot" /> Studio Next live status</span><h1>Governance you can verify</h1><p>Voxen records governance state on its configured GenLayer contract. Inspect the deployment, understand its checks, and distinguish configuration from a successful live read.</p></div><div className="proof-actions"><Link href="/explore" className="button">Explore</Link><Link href="/create" className="button primary">Create proposal</Link></div></header>
    <section className="proof-deployment panel" aria-labelledby="deployment-heading"><div className="panel-heading"><div><span className="eyebrow">Active deployment</span><h2 id="deployment-heading">Deployment proof</h2></div></div><dl className="proof-definition-list"><div><dt>Network</dt><dd>{voxenConfig.networkName}</dd></div><div><dt>Chain ID</dt><dd><CopyValue label="chain ID" value={String(voxenConfig.chainId)} /></dd></div><div><dt>RPC</dt><dd><CopyValue label="RPC URL" value={voxenConfig.rpc} /></dd></div><div><dt>Contract</dt><dd><CopyValue label="contract address" value={voxenConfig.contract} compact /></dd></div><div><dt>Deployment transaction</dt><dd><CopyValue label="deployment transaction" value={liveProof.deploymentTransaction} compact /></dd></div><div><dt>Contract state</dt><dd>Configured for {ACTIVE_NETWORK.name}; live readability is checked below.</dd></div></dl><LiveReadStatus /></section>
    <section className="proof-section-block" aria-labelledby="checks-heading"><div className="section-copy"><span className="eyebrow">Verification scope</span><h2 id="checks-heading">What the contract verifies</h2><p>These are the checks represented by the current product and contract reads. Exact values remain independently inspectable from the configured deployment.</p></div><div className="verification-grid">{checks.map(([title, explanation, method, afterward]) => <article key={title} className="verification-card"><span>{method}</span><h3>{title}</h3><p>{explanation}</p><small><strong>Verify afterward:</strong> {afterward}</small></article>)}</div></section>
    <section className="proof-consensus" aria-labelledby="consensus-heading"><div><span className="eyebrow">Consensus path</span><h2 id="consensus-heading">From a wallet action to finalized state</h2><p>Transactions can be accepted for processing without being final. Finality means validators reached consensus and the transaction executed successfully. Validators can also agree that an execution failed.</p></div><ol className="proof-trace"><li><strong>Wallet action</strong><span>The connected sender approves a proposed transaction.</span></li><li><strong>Transaction broadcast</strong><span>The transaction is sent to the configured network.</span></li><li><strong>Validator execution and consensus</strong><span>Validators execute contract logic; Governance Review is the nondeterministic review path.</span></li><li><strong>On-chain finalized state</strong><span>Only a finalized successful execution records the resulting state.</span></li></ol><p className="proof-note">POAP event verification is an experimental external check. It is not a validator identity proof.</p></section>
    <section className="boundary-section panel" aria-labelledby="boundaries-heading"><span className="eyebrow">System transparency</span><h2 id="boundaries-heading">What Voxen does not claim</h2><ul><li>PUBLIC eligibility enables open participation; it is not proof of personhood.</li><li>One wallet is not necessarily one human.</li><li>POAP verification is experimental and fails closed; external RPC availability can affect those checks.</li><li>Governance Review does not secretly override votes or break ties.</li><li>Ties remain ties unless a proposal explicitly provides a handling rule.</li></ul></section>
  </main>;
}
