"use client";
import { useEffect, useMemo, useState } from "react";
import type { ProposalForm } from "@/lib/voxen/create-proposal";
const CATALOG_URL = "/api/portal-poaps";
const MAX_CATALOG_PAGES = 20;
type Poap = { title: string; slug: string; artwork_url: string | null; event_start_at: string | null; legacy_poap_id: number | string | null };
const eventId = (p: Poap) => typeof p.legacy_poap_id === "number" && Number.isSafeInteger(p.legacy_poap_id) && p.legacy_poap_id >= 0 ? String(p.legacy_poap_id) : typeof p.legacy_poap_id === "string" && /^\d+$/.test(p.legacy_poap_id) ? p.legacy_poap_id : null;
function record(value: unknown): Poap | null { if (!value || typeof value !== "object") return null; const p = value as Record<string, unknown>; if (typeof p.title !== "string" || typeof p.slug !== "string" || (p.artwork_url !== null && typeof p.artwork_url !== "string") || (p.event_start_at !== null && typeof p.event_start_at !== "string") || (p.legacy_poap_id !== null && typeof p.legacy_poap_id !== "number" && typeof p.legacy_poap_id !== "string")) return null; return p as Poap; }
function dateLabel(value: string): string | null { const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date.toLocaleDateString(); }
async function catalog(signal: AbortSignal, search: string) { const items: Poap[] = []; for (let page = 1; page <= MAX_CATALOG_PAGES; page += 1) { const params = new URLSearchParams({ page: String(page), page_size: "100" }); if (search) params.set("search", search); const response = await fetch(`${CATALOG_URL}?${params}`, { credentials: "omit", signal }); if (!response.ok) throw Error("POAP catalog request failed."); const body: unknown = await response.json(); if (!body || typeof body !== "object" || !Array.isArray((body as { results?: unknown }).results) || typeof (body as { has_next?: unknown }).has_next !== "boolean") throw Error("Invalid POAP catalog response."); items.push(...(body as { results: unknown[] }).results.map(record).filter((p): p is Poap => p !== null)); if (!(body as { has_next: boolean }).has_next) return items; } throw Error("Invalid POAP catalog pagination."); }
export function CredentialPicker({ form, onChange }: { form: ProposalForm; onChange: (patch: Partial<ProposalForm>) => void }) {
 const [query, setQuery] = useState(""); const [items, setItems] = useState<Poap[]>([]); const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false); const [retry, setRetry] = useState(0);
 useEffect(() => { const abort = new AbortController(); setLoading(true); setFailed(false); void catalog(abort.signal, query.replace(/^#+/, "")).then((v) => !abort.signal.aborted && setItems(v)).catch(() => !abort.signal.aborted && setFailed(true)).finally(() => !abort.signal.aborted && setLoading(false)); return () => abort.abort(); }, [query, retry]);
 const results = useMemo(() => { const words = query.toLowerCase().trim().split(/\s+/).filter(Boolean).map((word) => word.replace(/^#+/, "")); return items.filter((p) => words.every((word) => `${p.title} ${p.slug}`.toLowerCase().includes(word))); }, [items, query]);
 return <div className="credential-picker"><div className="picker-heading"><div><h3>Choose a legacy POAP event</h3><p>Only badges with an authoritative numeric legacy event ID can be verified.</p></div></div><label>Search the POAP catalog<input type="search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search badges" /></label>
  {loading && <p role="status" className="small">Loading the POAP catalog…</p>}{failed && <><p role="alert" className="form-error">The POAP catalog is temporarily unavailable. No badge has been selected.</p><button type="button" className="button" onClick={() => setRetry((n) => n + 1)}>Retry catalog</button></>}
  {!loading && !failed && <p className="picker-count">{results.length} {results.length === 1 ? "result" : "results"}</p>}{!loading && !failed && !results.length && <p className="small">No matching POAP badges found.</p>}
  {!loading && !failed && <ul className="credential-results" aria-label="GenLayer Portal POAPs">{results.map((p) => { const id = eventId(p); const active = form.poapEventId === id; const date = p.event_start_at && dateLabel(p.event_start_at); return <li key={p.slug}><button type="button" className="credential-result" disabled={!id} aria-pressed={active} onClick={() => id && onChange({ poapEventId: id, label: p.title, poapMetadata: p.slug })}>{p.artwork_url && <img src={p.artwork_url} alt="" width={56} height={56} />}<strong>{p.title}</strong>{date && <span>{date}</span>}{id && <span>POAP event ID: {id}</span>}{active && <span>Selected</span>}</button>{!id && <p className="small muted">Portal-native badge — verification not yet publicly available.</p>}</li>; })}</ul>}
  {form.poapEventId && <section className="credential-selection"><h3>Selected voting requirement</h3><strong>{form.label}</strong><p>Legacy POAP event ID: <code>{form.poapEventId}</code></p><button type="button" className="button" onClick={() => onChange({ poapEventId: "", label: "", poapMetadata: "" })}>Clear selection</button></section>}
 </div>;
}
