"use client";
import { useState } from "react";
import type { Proposal } from "@/types/voxen";
import { useWallet } from "@/lib/genlayer/WalletProvider";
import type { EligibilityCheck } from "@/hooks/useVoxenEligibility";
import type { VoteController } from "@/hooks/useVoxenVote";
import { voxenConfig } from "@/lib/voxen/config";
import { votingEligibilityReason } from "@/lib/voxen/eligibility-status";
import { ConsensusTrace } from "./ConsensusTrace";
export function VotingPanel({ proposal: p, voting, eligibilityCheck }: { proposal: Proposal; voting?: VoteController; eligibilityCheck?: EligibilityCheck }) {
  const [selected, setSelected] = useState(""); const wallet = useWallet(); const now = Date.now();
  const active = p.status === "PUBLISHED" && now >= Date.parse(p.startsAt) && now < Date.parse(p.endsAt);
  const voteFinal = p.voteChangePolicy === "FINAL_ON_CAST" && voting?.stage === "finalized";
  const reason = voteFinal ? "You have voted. Your vote is final." : !wallet.isConnected ? "Connect your wallet to vote." : !wallet.isOnCorrectNetwork ? `Switch to ${voxenConfig.networkName} to vote.` : !active ? "Voting is not active right now." : eligibilityCheck?.isFetching ? "Checking eligibility…" : votingEligibilityReason(eligibilityCheck?.data?.eligible, eligibilityCheck?.data?.status);
  const visible = !p.talliesHidden;
  const total = p.participation;
  const lead = visible && total ? Math.max(...p.options.map((option) => option.votes)) : 0;
  return <section className="panel voting-panel" aria-labelledby="vote-heading"><div className="panel-heading"><div><h2 id="vote-heading">Cast your vote</h2><p>Select one option. {p.voteChangePolicy === "FINAL_ON_CAST" ? "Your vote is final once submitted." : "You may change it until voting closes."}</p></div>{visible && <span className="participation-count">{total} {total === 1 ? "vote" : "votes"}</span>}</div><fieldset disabled={voteFinal || voting?.pending} aria-describedby="vote-guidance"><legend className="sr-only">Choose a voting option</legend>{p.options.map((o) => { const percent = total ? Math.round((o.votes / total) * 100) : 0; const leading = visible && total > 0 && o.votes === lead; return <label className={`vote-option ${selected === o.id ? "chosen" : ""}`} key={o.id}><input type="radio" name="vote" value={o.id} checked={selected === o.id} disabled={!active || voting?.pending || voteFinal} onChange={() => setSelected(o.id)} /><span className="vote-option-label">{o.label}{leading && <small>Leading</small>}</span>{visible && <span className="vote-option-tally"><strong>{o.votes}</strong><span>{percent}%</span></span>} {visible && <i className="tally-bar" style={{ width: `${percent}%` }} aria-label={`${percent}% of votes`} />}</label>; })}</fieldset>{visible ? <p id="vote-guidance" className="vote-summary">{total ? "Live tallies reflect recorded participation." : "No votes have been recorded yet."}</p> : <p id="vote-guidance" className="vote-summary">Results are hidden until voting closes. No counts are shown.</p>}<ConsensusTrace voting={voting} /><button className="button primary full-width" disabled={!voting || !!reason || !selected || voting.pending} onClick={() => void voting?.cast(Number(selected))}>{voteFinal ? "You have voted. Your vote is final." : reason || (selected ? `Cast vote for ${p.options.find((option) => option.id === selected)?.label}` : "Select an option to vote")}</button><p className="vote-policy">{p.voteChangePolicy === "CHANGE_UNTIL_CLOSE" ? "Votes may be changed until the voting window closes." : "One wallet can cast one final vote."}</p>{p.result && <div className="final-result" role="status"><span>Final result</span><strong>{p.result === "TIED" ? "Tied result" : `Winner: ${p.result}`}</strong>{p.result === "TIED" && <p>No tie-breaking is applied.</p>}</div>}</section>;
}
