"use client";
import { useState } from "react";
import type { Proposal } from "@/types/voxen";
import { useWallet } from "@/lib/genlayer/WalletProvider";
import type { EligibilityCheck } from "@/hooks/useVoxenEligibility";
import type { VoteController } from "@/hooks/useVoxenVote";
import { voxenConfig } from "@/lib/voxen/config";
import { votingEligibilityReason } from "@/lib/voxen/eligibility-status";
export function VotingPanel({ proposal: p, voting, eligibilityCheck }: { proposal: Proposal; voting?: VoteController; eligibilityCheck?: EligibilityCheck }) {
  const [selected, setSelected] = useState(""); const wallet = useWallet(); const now = Date.now();
  const active = p.status === "PUBLISHED" && now >= Date.parse(p.startsAt) && now < Date.parse(p.endsAt);
  const voteFinal = p.voteChangePolicy === "FINAL_ON_CAST" && voting?.stage === "finalized";
  const reason = voteFinal ? "You have voted. Your vote is final." : !wallet.isConnected ? "Connect your wallet to vote." : !wallet.isOnCorrectNetwork ? `Switch to ${voxenConfig.networkName} to vote.` : !active ? "Voting is not active right now." : eligibilityCheck?.isFetching ? "Checking eligibility…" : votingEligibilityReason(eligibilityCheck?.data?.eligible, eligibilityCheck?.data?.status);
  const visible = !p.talliesHidden;
  const total = p.participation;
  return <section className="panel voting-panel"><h3>Proposal options</h3><fieldset disabled={voteFinal || voting?.pending}><legend className="sr-only">Choose a voting option</legend>{p.options.map((o) => { const percent = total ? Math.round((o.votes / total) * 100) : 0; return <label className={`vote-option ${selected === o.id ? "chosen" : ""}`} key={o.id}><input type="radio" name="vote" value={o.id} checked={selected === o.id} disabled={!active || voting?.pending || voteFinal} onChange={() => setSelected(o.id)} /><span>{o.label}</span>{visible && <><strong>{o.votes} · {percent}%</strong><i className="tally-bar" style={{ width: `${percent}%` }} aria-label={`${percent}% of votes`} /></>}</label>; })}</fieldset>{visible ? <p className="small muted">Total votes: {total}</p> : <p className="small muted">Results are hidden until voting closes.</p>}{voting?.stage && voting.stage !== "idle" && <div className={`vote-transaction vote-${voting.stage}`} role={voting.stage === "failed" ? "alert" : "status"}>{voting.stage === "finalized" ? <strong>Finalized — Vote recorded</strong> : <strong>{voting.stage === "submitting" ? "Waiting for wallet approval" : voting.stage === "submitted" ? "Transaction submitted" : voting.stage === "processing" || voting.stage === "accepted" ? "GenLayer consensus processing" : voting.stage === "failed" ? "Vote failed" : "Preparing vote"}</strong>}{voting.txId && <span>Transaction ID: <code>{voting.txId}</code></span>}{voting.message && <span>{voting.message}</span>}</div>}<button className="button primary full-width" disabled={!voting || !!reason || !selected || voting.pending} onClick={() => void voting?.cast(Number(selected))}>{reason || (p.voteChangePolicy === "CHANGE_UNTIL_CLOSE" ? "Cast or change vote" : "Cast vote")}</button><p className="small">{p.voteChangePolicy === "CHANGE_UNTIL_CLOSE" ? "Votes may be changed until close." : "Votes cannot be changed after submission."}</p>{p.result && <p>Final result: <strong>{p.result === "TIED" ? "TIED" : `WINNER — ${p.result}`}</strong>{p.result === "TIED" && " · No AI tie-breaking."}</p>}</section>;
}
