import type { Community, Proposal } from "@/types/voxen";
const owner = "0x1234567890aBcDEF1234567890abCDef12345678";
export const sampleSpaces: Community[] = [
  {
    id: "commons",
    name: "The Commons",
    description: "A shared space for the people building what comes next.",
    owner,
    admins: [owner],
    constitution:
      "Fund public goods with measurable community benefit. Proposals must state a budget, an accountable lead, and a delivery timeline. No individual may approve their own compensation.",
    permission: "OPEN",
    guardEnabled: true,
    nonCompliantPolicy: "BLOCK",
    active: true,
    symbol: "C",
    category: "Public goods",
  },
  {
    id: "protocol",
    name: "Protocol Collective",
    description: "Thoughtful decisions for an evolving protocol.",
    owner,
    admins: [],
    constitution:
      "Protocol changes require a technical specification and a public review period. Prioritize interoperability and open access.",
    permission: "OWNER_ADMINS",
    guardEnabled: true,
    nonCompliantPolicy: "WARN",
    active: true,
    symbol: "P",
    category: "Protocol",
  },
  {
    id: "fieldnotes",
    name: "Fieldnotes",
    description: "An independent community of makers and curious minds.",
    owner,
    admins: [],
    constitution:
      "Events should be accessible, community-led, and transparently budgeted.",
    permission: "OPEN",
    guardEnabled: false,
    nonCompliantPolicy: "WARN",
    active: true,
    symbol: "F",
    category: "Community",
  },
];
export const sampleProposals: Proposal[] = [
  {
    id: "commons-grants",
    title: "Fund the next wave of public goods",
    description:
      "Allocate 12,000 GEN from the community treasury to three open-source public goods projects. Each team will publish monthly progress updates, with funding released against agreed milestones. This proposal authorizes the allocation; voting itself requires no payment or token transfer.",
    spaceId: "commons",
    creator: owner,
    status: "OPEN",
    startsAt: "2026-09-01T09:00:00Z",
    endsAt: "2026-09-30T18:00:00Z",
    eligibility: { mode: "GEN_HOLDING", minimum: "100" },
    guard: {
      outcome: "COMPLIANT",
      risk: "LOW",
      confidence: 94,
      evidenceConsistency: "Consistent with the proposed scope",
      reason:
        "The proposal names a budget, delivery milestones, and public reporting requirements, consistent with the Community constitution.",
    },
    voteChangePolicy: "CHANGE_UNTIL_CLOSE",
    resultVisibility: "LIVE",
    options: [
      { id: "a", label: "Approve allocation", votes: 84 },
      { id: "b", label: "Revise the scope", votes: 21 },
      { id: "c", label: "Reject allocation", votes: 7 },
    ],
    participation: 112,
    source: "demo",
  },
  {
    id: "protocol-upgrade",
    title: "A more open developer ecosystem",
    description:
      "Adopt a community-maintained specification for developer tooling and a six-week public review process.",
    spaceId: "protocol",
    creator: owner,
    status: "REVIEW",
    startsAt: "2026-09-15T09:00:00Z",
    endsAt: "2026-10-01T18:00:00Z",
    eligibility: { mode: "GEN_HOLDING", minimum: "250" },
    guard: {
      outcome: "NEEDS_REVIEW",
      risk: "MEDIUM",
      confidence: 76,
      evidenceConsistency: "Supporting specification is incomplete",
      reason:
        "The proposal needs an accountable maintainer and a complete technical specification.",
    },
    voteChangePolicy: "FINAL_ON_CAST",
    resultVisibility: "HIDDEN_UNTIL_CLOSE",
    options: [
      { id: "a", label: "Adopt", votes: 0 },
      { id: "b", label: "Revisit", votes: 0 },
    ],
    participation: 0,
    source: "demo",
  },
  {
    id: "community-gathering",
    title: "Where should we gather next?",
    description:
      "Choose the location for our next community gathering. The community credential identifies eligible participants.",
    spaceId: "fieldnotes",
    creator: owner,
    status: "OPEN",
    startsAt: "2026-09-01T09:00:00Z",
    endsAt: "2026-09-25T18:00:00Z",
    eligibility: {
      mode: "POAP_NFT",
      chainId: 4221,
      contract: "0x9d7cDC2d47EdC8Fb697564F686cd028Db592504b",
      standard: "ERC1155",
      label: "Fieldnotes community credential",
      tokenId: "501",
    },
    voteChangePolicy: "CHANGE_UNTIL_CLOSE",
    resultVisibility: "HIDDEN_UNTIL_CLOSE",
    options: [
      { id: "a", label: "Lagos", votes: 0 },
      { id: "b", label: "Lisbon", votes: 0 },
    ],
    participation: 38,
    source: "demo",
  },
  {
    id: "commons-charter",
    title: "Adopt the community charter",
    description:
      "Adopt the founding constitution and transparent reporting requirements for The Commons.",
    spaceId: "commons",
    creator: owner,
    status: "FINALIZED",
    startsAt: "2026-08-01T09:00:00Z",
    endsAt: "2026-08-15T18:00:00Z",
    eligibility: { mode: "GEN_HOLDING", minimum: "100" },
    voteChangePolicy: "FINAL_ON_CAST",
    resultVisibility: "LIVE",
    options: [
      { id: "a", label: "Adopt", votes: 96 },
      { id: "b", label: "Reject", votes: 4 },
    ],
    participation: 100,
    result: "Adopt",
    source: "demo",
  },
];
